# Generated by Django 4.1 on 2022-12-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['state']},
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_id',
        ),
    ]
