# Generated by Django 4.1 on 2022-12-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_state_options_remove_state_state_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Voter'),
        ),
    ]
