# Generated by Django 4.1 on 2022-12-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_voter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='party_score',
        ),
    ]
