# Generated by Django 4.1 on 2022-12-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_remove_party_party_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcedlgaresult',
            name='party_score',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Party Score'),
        ),
        migrations.AddField(
            model_name='announcedpuresult',
            name='party_score',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Party Score'),
        ),
    ]
