# Generated by Django 4.1 on 2022-12-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_announcedlgaresult_party_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['ward_name']},
        ),
        migrations.AlterField(
            model_name='voter',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Voter'),
        ),
    ]
