# Generated by Django 4.1 on 2022-12-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_alter_ward_options_alter_voter_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollingunit',
            options={'ordering': ['poll_unit_id']},
        ),
        migrations.RenameField(
            model_name='pollingunit',
            old_name='poll_unique_id',
            new_name='poll_unit_id',
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='voter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='poll.voter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Polling Unit Number'),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='unique_ward_id',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Unique Ward ID'),
        ),
    ]
