# Generated by Django 4.1 on 2022-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_alter_pollingunit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['-lga_id']},
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
    ]
