# Generated by Django 4.1 on 2022-12-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_alter_ward_options_alter_pollingunit_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollingunit',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='TotalLgaPartyScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.SmallIntegerField(blank=True, default=0, verbose_name='Party Score')),
                ('lga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.lga')),
            ],
        ),
    ]
